CTF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('community/', include("community.urls")),
    path('news/', include("news.urls")),
    path('challenge/', include("challenge.urls")),
    path('chart/', include("chart.urls")),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

challenge/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.viewChallenge, name="challenge"),
    path('create_challenge',views.create_challenge,name="create_challenge"),
    path('create_challenge_quizz/<str:pk>/',views.create_challenge_quizz,name="create_challenge_quizz"),
    path('display_quizzes/<str:pk>/',views.display_quizzes,name="display_quizzes"),
    path('display_quizzes/<str:pk>/edit_quizz/<str:pk1>/',views.edit_quizz,name="edit_quizz"),
    path('join_challenge/<str:pk>/',views.join_challenge,name="join_challenge"),
    path('register_challenge/<str:pk>/',views.register_challenge,name="register_challenge"),
    path('expired_challenge/<str:pk>/',views.expired_challenge,name="expired_challenge"),
    path('play_challenge/<str:pk>/',views.play_challenge,name="play_challenge"),
    path('play_challenge/<str:pk>/play_challenge_quizz/<str:pk1>/',views.play_challenge_quizz,name="play_challenge_quizz"),
]

challenge/models.py
from django.db import models

# Create your models here.


class Challenge(models.Model):
    name = models.CharField(max_length=200,  null=False, blank=False)
    owner = models.CharField(max_length=200,  null=False, blank=False)
    public = models.BooleanField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Quizz(models.Model):
    challenge_id = models.IntegerField()
    name = models.CharField(max_length=200,  null=True, blank=True)
    question = models.TextField(null=False, blank=False)
    answer = models.TextField(null=False, blank=False)
    point = models.IntegerField()
    file_content = models.FileField(upload_to='files/',null=True,blank=True)

    def __str__(self):
        return str(self.challenge_id)

class Hint(models.Model):
    quizz_id = models.IntegerField()
    content = models.TextField(null=False, blank=False)
    point = models.IntegerField()

    def __str__(self):
        return str(self.quizz_id)

class Answer(models.Model):
    username=models.CharField(max_length=20,  null=True, blank=True)
    challenge_id = models.IntegerField()
    quizz_id = models.IntegerField()
    answer = models.TextField(null=False, blank=False)
    point = models.IntegerField()
    status = models.CharField(max_length=10)
    

    def __str__(self):
        return self.username

challenge/forms.py
from django import forms
from django.forms import ModelForm
from .models import Challenge, Quizz, Hint, Answer

class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'

class ChallengeForm(ModelForm):
    class Meta:
        model = Challenge
        fields = '__all__'
        exclude = ['owner']
        widgets = {
            'date_start' : DateTimeInput(),
            'date_end' : DateTimeInput()
        }

class QuizzForm(ModelForm):
    class Meta:
        model = Quizz
        fields = '__all__'
        exclude=['challenge_id']

class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['answer']

challenge/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from django.core.files.storage import FileSystemStorage

from .forms import ChallengeForm, QuizzForm, AnswerForm
from .forms import Challenge, Quizz, Hint, Answer

from community.models import User, Note

# Create your views here.


def viewChallenge(request):
    challenges = {}
    if request.user.is_superuser:
        challenges = Challenge.objects.all().filter(owner=request.user)
        is_super = 'yes'
    else:
        is_super = 'no'

    print(is_super)

    context = {'challenges': challenges, 'is_super': is_super}
    return render(request, 'challenge.html', context)


@login_required(login_url='login')
def create_challenge(request):

    form = ChallengeForm()
    if request.method == 'POST':
        form = ChallengeForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name')
            date_start = request.POST.get('date_start')
            date_end = request.POST.get('date_end')
            description = request.POST.get('description')
            public = request.POST.get('public')

            challenge = Challenge.objects.create(
                name=name,
                owner=str(request.user),
                date_start=date_start,
                date_end=date_end,
                description=description,
                public=public
            )
            challenge.save()
            # print(form)
            return redirect(create_challenge_quizz, pk=challenge.id)
            # return redirect(f'create_challenge_quizz/{challenge.id}/')

    context = {'form': form}
    return render(request, 'create_challenge.html', context)


@login_required(login_url='login')
def create_challenge_quizz(request, pk):
    challenge = Challenge.objects.get(id=pk)
    name = challenge.name
    context = {'name': name}
    form = QuizzForm()

    if request.method == 'POST':
        form = QuizzForm(request.POST, request.FILES)
        if form.is_valid():
            _name = request.POST.get('name')
            _question = request.POST.get('question')
            _answer = request.POST.get('answer')
            _point = request.POST.get('point')

            hints = request.POST.getlist('hint')
            hint_points = request.POST.getlist('hint_point')

            file = request.FILES.get('file_content')

            if not file:
                file=None

            quizz = Quizz.objects.create(
                challenge_id=pk,
                name=_name,
                question=_question,
                answer=_answer,
                point=_point,
                file_content=file
            )
            quizz.save()

            for content, hint_point in zip(hints,hint_points):
                hint = Hint.objects.create(
                    quizz_id=quizz.id,
                    content=content,
                    point=hint_point
                )
                hint.save()

    context = {'form': form, 'challenge': challenge}
    return render(request, 'create_challenge_quizz.html', context)


@login_required(login_url='login')
def display_quizzes(request, pk):
    challenge = Challenge.objects.get(id=pk)
    quizzes = Quizz.objects.all().filter(challenge_id=pk).values(
        'id', 'name', 'question', 'answer', 'point', 'file_content')

    hint_counts = []

    if request.method == 'POST' and 'Delete' in request.POST:
        print('yes')
        quizzes = Quizz.objects.filter(challenge_id=pk)
        for quizz in quizzes:
            id = quizz.id
            Hint.objects.filter(quizz_id=id).delete()
        quizzes.delete()
        challenge.delete()
        return redirect(viewChallenge)

    if request.method == 'POST':
        print(request.POST)

    if request.method == 'POST' and 'changePrivate' in request.POST:
        print('yes')
        Challenge.objects.filter(id=pk).update(public="False")
        return redirect(display_quizzes,pk)
    
    if request.method == 'POST' and 'changePublic' in request.POST:
        print('yess')
        Challenge.objects.filter(id=pk).update(public="True")
        return redirect(display_quizzes,pk)

    for quizz in quizzes:
        id = quizz['id']
        hint_count = Hint.objects.all().filter(quizz_id=id).count()
        hint_counts.append(hint_count)

    context = {'challenge': challenge,
               'quizzes': quizzes, 'hintCounts': hint_counts}

    return render(request, 'display_quizzes.html', context)


@login_required(login_url='login')
def edit_quizz(request, pk, pk1):
    quizz = Quizz.objects.get(id=pk1)

    form = QuizzForm()

    hints = Hint.objects.filter(quizz_id=pk1).values('content', 'point')

    if request.method == 'POST':
        if'Submit' in request.POST:
            form = QuizzForm(request.POST, request.FILES, instance=quizz)
            # print(form)
            if form.is_valid():
                Hint.objects.filter(quizz_id=pk1).delete()
                hints = request.POST.getlist('hint')
                hint_points = request.POST.getlist('hint_point')
                # print(hints)

                for content, hint_point in zip(hints, hint_points):
                    hint = Hint.objects.create(
                        quizz_id=pk1,
                        content=content,
                        point=hint_point
                    )
                    hint.save()

                form.save()
        else:
            quizz.delete()
        return redirect(display_quizzes, pk=pk)

        # form=QuizzForm(request.POST)
        # hintss = request.POST.getlist('hint')
        # hint_points = request.POST.getlist('hint_point')
        # print(hintss)

    context = {'form': form, 'quizz': quizz,
               'challenge_id': pk, 'hints': hints}
    return render(request, 'edit_a_quizz.html', context)


def join_challenge(request, pk):
    challenge = Challenge.objects.get(id=pk)

    creator = User.objects.get(username=challenge.owner)
    creator_name = creator.name

    context = {'challenge': challenge, 'creator_name': creator_name}
    return render(request, 'join_challenge.html', context)


def register_challenge(request, pk):
    challenge = Challenge.objects.get(id=pk)

    creator = User.objects.get(username=challenge.owner)
    creator_name = creator.name

    try:
        obj = Note.objects.get(challenge_id=challenge.id)
        registered = 'yes'
    except Note.DoesNotExist:
        registered = 'no'

    if request.method == 'POST':
        _content = challenge.name+" has started. Join us now!"
        note = Note.objects.create(
            user=request.user,
            date=challenge.date_start,
            content=_content,
            challenge_id=challenge.id
        )
        note.save()
        return redirect('upcoming')

    # print(creator_name)
    context = {'challenge': challenge,
               'creator_name': creator_name, 'registered': registered}
    return render(request, 'register_challenge.html', context)


def expired_challenge(request, pk):
    challenge = Challenge.objects.get(id=pk)

    creator = User.objects.get(username=challenge.owner)
    creator_name = creator.name

    context = {'challenge': challenge, 'creator_name': creator_name}
    return render(request, 'expired_challenge.html', context)


def play_challenge(request, pk):
    challenge = Challenge.objects.get(id=pk)
    quizzes = Quizz.objects.all().filter(challenge_id=pk).values(
        'id', 'name', 'question', 'answer', 'point', 'file_content')

    completed = {}
    status = {}

    score = 0

    for quizz in quizzes:
        try:
            obj = Answer.objects.get(quizz_id=quizz['id'],username=request.user)
            completed[quizz['id']] = 'yes'
            if obj.status == 'True':
                status[quizz['id']] ="True"
            else:
                status[quizz['id']] ="False"
            score += obj.point
        except Answer.DoesNotExist:
            completed[quizz['id']] = 'no' 
            pass

    context = {'challenge': challenge, 'quizzes': quizzes,
               'completed': completed, 'score': score, 'status':status}
    return render(request, 'play_challenge.html', context)

from datetime import date, datetime
from django.utils import timezone

def play_challenge_quizz(request, pk, pk1):
    challenge = Challenge.objects.get(id=pk)
    quizz = Quizz.objects.get(id=pk1)
    hints = Hint.objects.filter(quizz_id=quizz.id)

    _point = 0
    _status = "False"
    now = timezone.now()
    date = now.strftime("%Y-%m-%d %H:%M:%S")
    if request.method == 'POST':
        _answer = request.POST.get('answer')
        minus_point = request.POST.get('minus-point')
        # print('begin')
        # print(minus_point)
        if _answer == quizz.answer:
            _point = quizz.point-int(minus_point)
            _status="True"
        else:
            _point = 0
            _status="False"

        try:
            obj = Answer.objects.get(quizz_id=quizz.id,username=request.user.username)
            _point = int(75*int(_point)/100)
            obj.point = _point
            obj.status=_status
            obj.save()
        except Answer.DoesNotExist:
            answer_obj = Answer.objects.create(
                challenge_id=challenge.id,
                username=request.user.username,
                quizz_id=quizz.id,
                answer=_answer,
                point=_point,
                status=_status
            )
            answer_obj.save()

        return redirect(play_challenge, pk=pk)

    # print(hints)

    context = {'challenge': challenge, 'quizz': quizz, 'hints': hints}
    return render(request, 'play_challenge_quizz.html', context)

challenge/templates/edit_a_quizz.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CTFGames - Cybersecurity Competition</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/challenge.css' %}?{% now " U" %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'main/logo-black.png' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>
    {% include 'navbar.html' %}
    {% block content %}
    <div class="container text-center">
        <div class="h1">Create quizzes</div>
    </div>

    <form action="" method="post" autocomplete="off" enctype="multipart/form-data">
        <!-- Quizz Section -->

        <div class="container quizz-container">
            <div class="card col-sm-7 pt-0 rounded-4 mt-5 mx-auto" id="quizz-card1">
                <div class="container text-end w-100">
                    <button type="button" onclick="delQuizz(event)" id="delQuizzBtn"
                        class="btn-close-white btn-close me-0" aria-label="Close"></button>
                </div>
                {% csrf_token %}
                <!-- Name -->
                <label for="name" class="text-capitalize ms-3" onclick="console.log('{{quizz.file_content}}')">
                    Name:
                </label>
                <div class="form-control bg-transparent border-0">
                    <input type="text" class="form-control bg-transparent border-2 text-light fs-4"
                        value="{{quizz.name}}" style="border-color: #696d97;" name="name" id="name">
                </div>

                <!-- Question -->
                <label for="question" class="text-capitalize ms-3">
                    Question:
                </label>
                <div class="form-control bg-transparent border-0">
                    <textarea class="form-control bg-transparent border-2 text-light fs-4"
                        style="border-color: #696d97;" name="question" id="question">{{quizz.question}}</textarea>
                </div>

                <!-- Answer -->
                <label for="answer" class="text-capitalize ms-3">
                    answer:
                </label>
                <div class="form-control bg-transparent border-0">
                    <textarea class="form-control bg-transparent border-2 text-light fs-4"
                        style="border-color: #696d97;" name="answer" id="answer">{{quizz.answer}}</textarea>
                </div>

                <!-- Point -->
                <label for="point" class="text-capitalize ms-3">
                    point:
                </label>
                <div class="form-control bg-transparent border-0">
                    <input type="text" class="form-control bg-transparent border-2 text-light fs-4"
                        value="{{quizz.point}}" style="border-color: #696d97;" name="point" id="point">
                </div>

                <!-- Add file -->
                {% if quizz.file_content == '' %}
                <div class="row ms-3">
                    <div class="form-check col-2" onclick="addfile(event)">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                        <label class="form-check-label" for="flexCheckDefault">
                            Add file
                        </label>
                    </div>
                    <!-- <div class="ms-3 col-3" id="uploadElement">
                        <input type="file" name="file_content" id="id_file_content">
                    </div> -->
                </div>
                {% else %}
                <div class="row ms-3">
                    <div class="form-check col-2">
                        <input class="form-check-input" onclick="addfile(event)" type="checkbox" value=""
                            id="flexCheckDefault" checked>
                        <label class="form-check-label" for="flexCheckDefault">
                            Add file
                        </label>
                    </div>
                    <div class="ms-3 col-9" id="uploadElement">
                        <input type="file" name="file_content" id="id_file_content" class="d-none"
                            value="{{quizz.file_content}}">
                        <label for="id_file_content">{{quizz.file_content}}</label>
                        <input type="checkbox" name="file_content-clear" id="file_content-clear_id">
                        <label for="file_content-clear_id">Clear</label><br>
                    </div>
                </div>
                {% endif %}
                <div style="width: 100%;" id="hint-container">
                    {% for hint in hints %}
                    <div class="input-group form-control bg-transparent border-0 hint-element">
                        <input type="" class="d-none" id="quizz_id" name="quizz_id">
                        <span class="input-group-text bg-transparent border-2 text-light fs-4 my-3">Hint</span>
                        <input type="text" placeholder="Hint" style="width: 350px;" aria-label="Hint"
                            class="form-control bg-transparent border-2 text-light fs-4 my-3" name="hint"
                            value="{{hint.content}}">
                        <input type="text" placeholder="Points" style="min-width: 70px;" aria-label="Point"
                            class="form-control bg-transparent border-2 text-light fs-4 my-3" name="hint_point"
                            value="{{hint.point}}">
                        <button onclick="delHint(event)" class="btn btn-outline-danger my-3 fs-4" type="button"
                            id="hintDelBtn">Discard</button>
                    </div>
                    {% endfor %}
                </div>

                <div class="text-end col-12">
                    <button onclick="addHint(event)" type="button" class="btn btn-sm btn-light mx-auto mb-2 me-3"
                        style="background-color: #696d97!important;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-plus" viewBox="0 0 16 16">
                            <path
                                d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z">
                            </path>
                        </svg>
                        Add a hint
                    </button>
                </div>
            </div>

        </div>

        <div class="container row mt-5 mb-3 text-center">
            <div class="input-group d-inline-block">
                <button type="button" onclick="location.href='/challenge/display_quizzes/{{challenge_id}}/'"
                    class="btn btn-lg btn-danger my-auto" style="background-color: #c93232!important;">
                    Cancel
                </button>
                <button type="submit" name="Delete" onclick="location.href='/challenge/display_quizzes/{{challenge_id}}/'"
                    class="btn btn-lg btn-danger my-auto" style="background-color: #c93232!important;">
                    Delete
                </button>
                <button type="submit" name="Submit" class="btn btn-lg btn-light my-auto" style="background-color: #696d97!important;">
                    Submit
                </button>
            </div>
        </div>

    </form>



    {% endblock content %}
    {% include 'footer.html' %}
    <script>

        function addfile(event) {
            if (event.target.checked == true) {
                const container = event.target.parentElement.parentElement;
                const newElement = document.createElement('DIV');
                newElement.className = 'ms-3 col-3';
                newElement.id = 'uploadElement'
                newElement.innerHTML = '<input type="file" name="file_content" id="id_file_content">';
                container.appendChild(newElement)
            }
            else {
                event.target.parentElement.parentElement.querySelector('#uploadElement').remove()
            }
        }

        function addHint(event) {
            const container = event.target.parentElement.parentElement.querySelector('#hint-container');

            const newcard = document.createElement('DIV');
            newcard.className = 'input-group form-control bg-transparent border-0 hint-element';
            newcard.innerHTML = '<input type="" class="d-none" id="quizz_id" name="quizz_id"><span class="input-group-text bg-transparent border-2 text-light fs-4 my-3">Hint</span> <input type="text" placeholder="Hint" style="width: 350px;" aria-label="Hint" class="form-control bg-transparent border-2 text-light fs-4 my-3" name="hint"> <input type="text" placeholder="Points" style="min-width: 70px;" aria-label="Point" class="form-control bg-transparent border-2 text-light fs-4 my-3" name="hint_point"> <button onclick="delHint(event)" class="btn btn-outline-danger my-3 fs-4" type="button" id="hintDelBtn">Discard</button>'

            container.appendChild(newcard);

            var arr = event.target.parentElement.parentElement.getAttribute('id');
            console.log(arr);
            var arr2 = event.target.parentElement.parentElement.querySelectorAll(".hint-element");
            let nodeList = event.target.parentElement.parentElement.querySelectorAll(".hint-element");
            console.log(nodeList);
            for (let i = 0; i < nodeList.length; i++) {
                nodeList[i].children[0].value = arr;
                console.log(nodeList[i].children[0].value);
            }
        }

        function delHint(event) {
            event.target.parentElement.remove();
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>

</html>

challenge/templates/expired_challenge.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CTFGames - Cybersecurity Competition</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/challenge.css' %}?{% now " U" %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'main/logo-black.png' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body class="d-flex flex-column min-vh-100">
    {% include 'navbar.html' %}
    {% block content %}

    <div class="container mb-4">
        <div class="row">
            <div class="card col-sm mx-auto pt-1 rounded-4 ms-3" style="background-color: #3f4156!important;">
                {% csrf_token %}
                <div class="card-title mx-auto mt-3">{{challenge.name}}</div>
                <div class="card-body d-inline">
                    Start from: {{challenge.date_start}} <br>
                    To: {{challenge.date_end}} <br>
                    Created by: {{creator_name}} <br>
                    Description: {{challenge.description}}
                </div>
            </div>
            {% load static %}
            <div class="col col-lg-4 text-end">
                <img class="img-fluid text-end d-inline" style="height: 250px; width: 378px;"
                    src="{% static 'main/images/thumb.png' %}">
            </div>
        </div>
    </div>

    <div class="container text-center">
        <div class="h2">You can't do anything with expired challenge! <br></div>
        <a href="{% url 'expired' %}">Click here to come back.</a>
    </div>


    {% endblock content %}
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>

</html>

challenge/templates/play_challenge_quizz.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CTFGames - Cybersecurity Competition</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/challenge.css' %}?{% now " U" %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'main/logo-black.png' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body class="d-flex flex-column min-vh-100">
    {% include 'navbar.html' %}
    {% block content %}

    <form action="" method="POST">
        {% csrf_token %}
        <div class="container text-center mb-4">
            <div class="card w-50 mx-auto text-center">
                <div class="card-title border-bottom">{{quizz.name}}</div>
                <div class="card-body text-start">
                    <div class="ms-3">
                        Question: {{quizz.question}} <br>
                    </div>
                    <div class="ms-3">
                        Points: {{quizz.point}} <br>
                    </div>
                    <div class="ms-3">
                        {% for hint in hints %}
                        <div>
                            Hint {{forloop.counter}}:
                            <span style="color: #71c6dd;" class="clickable-element" onclick="event.target.innerHTML='{{hint.content}}'; num+=parseInt('{{hint.point}}');
                                getPoint();">Click
                                to show hint</span>
                            (-{{hint.point}} pts)<br>
                        </div>
                        {% endfor %}
                    </div>
                    {% if quizz.file_content %}
                    <div class="ms-3">
                        File:
                        <a href="{{quizz.file_content.url}}" class="btn btn-lg btn-primary px-3 py-2"
                            style="background-color: #696d97!important;">
                            Download file
                        </a>
                    </div>
                    {% endif %}

                    <label for="answer" class="text-capitalize ms-3">
                        answer:
                    </label>
                    <div class="form-control bg-transparent border-0">
                        <textarea class="form-control bg-transparent border-2 text-light fs-4"
                            style="border-color: #696d97;" name="answer" id="id_answer" required></textarea>
                    </div>

                    <input type="text" class="d-none" id="minus-point" name="minus-point" value=0>
                </div>
            </div>
        </div>

        <div class="container row mt-0">
            <!-- Button Cancel -->
            <div class="text-end col-8">
                <button type="button" onclick="location.href='{% url 'play_challenge' challenge.id %}'"
                    class="btn btn-lg btn-danger me-1 my-auto" style="background-color: #c93232!important;">
                    Cancel
                </button>
            </div>
            <!-- Button Submit -->
            <div class="text-end col-1">
                <button type="submit" class="btn btn-lg btn-light my-auto" style="background-color: #696d97!important;">
                    Submit
                </button>
            </div>
        </div>
    </form>


    {% endblock content %}
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <script type="text/javascript">
        var num = 0;
        function showHint(event) {
            container = event.target;
            container.innerHTML = '{{hint.content}}';
        }

        function getPoint() {
            event.target.onclick = false;
            document.getElementById('minus-point').value = num;
            console.log(num)
        }
    </script>
</body>

</html>